name: Main CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: Test action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run composite action
        uses: jb-0/composite-action@main